version: "3.7"
services:

    app:
        build:
            args:
                user: AJIMENEZ
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: enviame
        container_name: enviame-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - enviame

    db:
        image: mysql:5.7
        container_name: enviame-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - enviame

    nginx:
        image: nginx:1.17-alpine
        container_name: enviame-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - enviame

networks:
  enviame:
    driver: bridge